development signup
kdh7037/MatchMaker-be pull request #3
Opened 2023-01-11 14:36 UTC by kdh7037

signup update

2023-01-11 14:38 UTC, ATRON3273 reviewed
도와줘요 백엔드맨 @kain6245

2023-01-11 14:38 UTC, gunhoflash requested changes

2023-01-11 14:38 UTC, gunhoflash commented on src/main/java/gfhouse/matchmaker/controller/UserController.java
> +    public User signup(@RequestBody UserDto userDto){
```suggestion
    public User signup(@RequestBody UserDto userDto) {
```
일관된 코드 스타일을 유지하는 것이 좋겠습니다.

2023-01-11 14:38 UTC, gunhoflash commented on src/main/java/gfhouse/matchmaker/dto/UserDto.java
> +    public UserDto(User user){
```suggestion
    public UserDto(User user) {
```

2023-01-11 14:41 UTC, gunhoflash approved these changes

2023-01-12 12:09 UTC, kain6245 commented on src/main/java/gfhouse/matchmaker/controller/UserController.java
> +    }
Lombok의 @RequiredArgsConstructor를 쓰면 좀 더 편하게 주입받을 수 있습니다
이건 컨벤션 정하기 나름일 것 같은데 어떻게 할까요

2023-01-12 12:09 UTC, kain6245 commented on src/main/resources/templates/signup_form.html
> +hello
이건 어디서 쓰나여??

2023-01-12 13:04 UTC, kdh7037 commented on src/main/java/gfhouse/matchmaker/controller/UserController.java
> +    }
공부해보고 편한 방법으로 적용시키겠습니다

2023-01-12 13:04 UTC, kdh7037 commented on src/main/resources/templates/signup_form.html
> +hello
단순히 공부를 위해 예시로 넣었던 더미 파일입니다. 의미는 없어요

2023-01-13 05:02 UTC, kain6245 commented on src/main/resources/templates/signup_form.html
> +hello
넹 그럼 지워주세여

2023-01-13 05:05 UTC, kain6245 commented on src/main/java/gfhouse/matchmaker/controller/UserController.java
> +    }
ㅇㅋㅇㅋ~
내 생각엔
1. 이미 롬복을 쓰고 있으니까 생성자도 롬복으로 만든다
-> 뭔가 의존성이 추가될 때 생성자를 수정 안해줘도 되어 편리하다
2. Dto와 같은 응답객체에만 부분적으로 롬복을 활용하고 서비스 에서 롬복 의존성을 제거한다.
-> 나중에 롬복이 변경되거나 제거해야 하는 상황이 생겼을 때 서비스는 영향받지 않는다.

더 마음가는걸로 ㄱㄱ

2023-01-17 14:43 UTC, merged